//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolZhelnov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public Doc()
        {
            this.Zapis = new HashSet<Zapis>();
        }
    
        public int kodDoca { get; set; }
        public string FIODoc { get; set; }
        public string kodSpec { get; set; }
        public System.DateTime birthDoc { get; set; }
        public int PhoneDoc { get; set; }
        public int Kabinet { get; set; }
    
        public virtual ICollection<Zapis> Zapis { get; set; }
    }
}
