//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolZhelnov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        public Pacient()
        {
            this.Zapis = new HashSet<Zapis>();
        }
    
        public int kodPacienta { get; set; }
        public int Snils { get; set; }
        public string FIOPacient { get; set; }
        public System.DateTime Birth { get; set; }
        public int Phone { get; set; }
    
        public virtual ICollection<Zapis> Zapis { get; set; }
    }
}
