//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolZhelnov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int kodZapis { get; set; }
        public System.DateTime datetimeZapis { get; set; }
        public int kodDoca { get; set; }
        public int kodPacienta { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
